### ISSUE TITLE
flash不生效

### ISSUE THREAD

**Issue by jun-zhang** [tishion/QCefView#10]
在OnBeforeCommandLineProcessing添加command_line->AppendSwitch("enable-system-flash");不生效

**Comment by tishion** [comment]
@jun-zhang 

I don't know whether the CEF supports it or not. This projects is only for integrating the CEF with QT, so could you please take a look at some other topics about CEF enable flash?
___
我并不清楚CEF目前是否继续支持Flash插件， 早些时候CEF支持所谓的PPAPI Flash插件（chrom浏览器中包含的）但是现在是否继续支持我也不得知，所以你可以自行搜索一下相关问题么？这个项目仅仅是作一个CEF和QT的集成的，至于具体的CEF的细节功能我都没有太过深入的探究，而且推荐使用H5来代替你的flash功能

**Comment by jun-zhang** [comment]
Using the same version of the cef example can be loaded flash plugin, I don't know what causes cef can't load the flash.

**Comment by lgxZJ** [comment]
@jun-zhang  same problem, using cef directly can load the flash plugin, but using QCefView(coding inside OnBeforeCommandLineProcessing() method) cannot make it work.

**Comment by lgxZJ** [comment]
@jun-zhang  @tishion  #24

**Comment by jun-zhang** [comment]
//browserSettings.plugins = STATE_ENABLED;	// disable all plugins

**Comment by BBDXF** [comment]
# 启用Flash
```cpp
// QCefViewBrowserApp.cpp line 24
void QCefViewBrowserApp::OnBeforeCommandLineProcessing(
	const CefString& process_type, 
	CefRefPtr<CefCommandLine> command_line)
{
	command_line->AppendSwitch("disable-spell-checking");
	//command_line->AppendSwitch("disable-extensions");
	command_line->AppendSwitch("disable-pdf-extension");
	command_line->AppendSwitch("enable-direct-write");
	command_line->AppendSwitch("allow-file-access-from-files");
	command_line->AppendSwitchWithValue("renderer-process-limit", "1");
	command_line->AppendSwitch("--disable-web-security");//关闭同源策略
	command_line->AppendSwitch("--enable-system-flash");//使用系统flash
}

// QCefView.cpp line 39
browserSettings.plugins = STATE_DEFAULT;	// disable all plugins
```
