### ISSUE TITLE
Questions about MP3 and MP4 support

### ISSUE THREAD

**Issue by lgxZJ** [tishion/QCefView#14]
@tishion  Hey gay, i'm here again for asking whether the QCefView supports playing mp3 and mp4 files?

**Comment by lgxZJ** [comment]
@tishion

**Comment by tishion** [comment]
If you are going to play audio and video in the webpage displayed by QCefView i believe it will works well

**Comment by lgxZJ** [comment]
@tishion I was informed that that CEF does not support mp3 and mp4, have you tested ever?

**Comment by tishion** [comment]
I tried with html5 test site. My version doesn't support. You need to find
another version or change your content yo HTML5

**Comment by lgxZJ** [comment]
@tishion  Ok, thanks for you reply!
