### ISSUE TITLE
crash when I close window on debug mode

### ISSUE THREAD

**Issue by zhulingbiezhi** [tishion/QCefView#18]
Can you help me ?  Now I  have a serious problem, the program crash when close the browser window on debug mode. the fail message is "[0905/100719:FATAL:browser_main.cc(203)] Check failed: 0 == CefURLRequestContext::DebugObjCt (0 vs. 1)"

**Comment by zhulingbiezhi** [comment]
https://github.com/zhulingbiezhi/cef-chrome, this is my source code on github

**Comment by tishion** [comment]
@zhulingbiezhi   This is a known issue, because I didn't handle the CEF un-initialization correctly. Thank you for your feedback. I will change this to a bug.

**Comment by zhulingbiezhi** [comment]
ok, thank you for your reply.

**Comment by tishion** [comment]
Try the latest version.
