### ISSUE TITLE
change the CEF version,But auto reload

### ISSUE THREAD

**Issue by sunpeishuai** [tishion/QCefView#20]
I change the CEF version to 3163
but the QCefView auto reload
sub-process always crash
Help me think about where the bug

**Comment by sunpeishuai** [comment]
wow!
sub_process auto crash~~

**Comment by tishion** [comment]
Just attach a debugger to the sub process and get the crash call stack.

**Comment by sunpeishuai** [comment]
crash libcef.dll

**Comment by sunpeishuai** [comment]
oh!
Because icudtl.dat hasn't been updated
Thank you very much!

**Comment by tishion** [comment]
Glad to see you have resolved your problem. :) 

Can you please close this issue?
