### ISSUE TITLE
QCefView::browserGoForward() mistakes

### ISSUE THREAD

**Issue by lgxZJ** [tishion/QCefView#25]
file:    QCefView.cpp
func:  QCefView::Implementation::browserGoForward()
line:   122

details:   wrong cef function ( CanGoForward() ) called, it should be GoForward() instead. please check.

**Comment by tishion** [comment]
so can you make a pull request to fix what you found? I appreciate it you
can become a contributor.

Thanks a lot!

**Comment by lgxZJ** [comment]
@tishion  glad to do it.
