### ISSUE TITLE
咨询网页中<select>标签不显示下拉框

### ISSUE THREAD

**Issue by beyond0851** [tishion/QCefView#27]
您好，我在内嵌的html页面内有\<select>标签，用该cef封装无法显示下拉框里的内容。
例如："\<select>\<option>11\</option>\<option>22\</option>\</select>" ，
想咨询下是什么问题呢？谢谢。

**Comment by tishion** [comment]
最近几天没办法处理这个问题，我会在下周尽快验证修复。谢谢。

**Comment by tishion** [comment]
@beyond0851   无法重现你所说的问题。
