### ISSUE TITLE
Load HTML failed after cef update (3.3239.1706.gcd33baa)

### ISSUE THREAD

**Issue by NOUT-SIMAX** [tishion/QCefView#30]
Hello, 
I update cef to version 3.3239.1706.gcd33baa
I compiled cef wrapper like indicated in the doc
I copied the files

Release version of QCefViewTest is OK but Debug version of QCefViewTest failed with
[1220/173505.334:ERROR:icc_profile.cc(282)] Failed to accurately approximate transfer function, error: 26.4684/256
[1220/173509.715:FATAL:frame_ctocpp.cc(182)] Check failed: !url.empty(). 
in the output.

What am I doing wrong ?

I am using Visual Studio 2013

**Comment by tishion** [comment]
The error message shows the URL is empty, can you confirm this?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by NOUT-SIMAX** [comment]
I am using your project without modification, except for the update of the cef version.

Indeed, the html page isn't showing in debug. In release, the page shows.

**Comment by tishion** [comment]
@NOUT-SIMAX   have your solved this problem by yourself?

**Comment by NOUT-SIMAX** [comment]
No, I can not manage to make the test project work in debug mode

**Comment by solarisx** [comment]
Hi, I get the same error with Debug settings. With Release it works. I upgraded to cef_binary_3.3282.1732.g973997f_windows32 and patched to code for it slightly. 

`[0208/143900.076:FATAL:frame_ctocpp.cc(182)] Check failed: !url.empty(). `

**Comment by NOUT-SIMAX** [comment]
Found my error, in Debug mode, you must use cef Release Dependance.
