### ISSUE TITLE
flash显示问题

### ISSUE THREAD

**Issue by lucaswang420** [tishion/QCefView#33]
我按照网上说的方法，在你的QCefViewBrowserApp::OnBeforeCommandLineProcessing函数中加入了以下代码：
command_line->AppendSwitchWithValue("ppapi-flash-version", "22.0.0.209");
command_line->AppendSwitchWithValue("ppapi-flash-path", "PepperFlash\\pepflashplayer.dll");

但是好像flash未能正常加载。是否是因为我加代码的地方有问题还是你的项目需要另外的配置。这两行代码我直接加在cef的测试例子里面是可以正常加载flash的。

**Comment by lucaswang420** [comment]
原来是楼主代码禁用了，
CefBrowserSettings browserSettings;
browserSettings.plugins = STATE_DISABLED;	// disable all plugins，
去掉了这个就可以了

**Comment by tishion** [comment]
:)

**Comment by BBDXF** [comment]
还需要如下设置： 
```cpp
void QCefViewBrowserApp::OnBeforeCommandLineProcessing(
	const CefString& process_type, 
	CefRefPtr<CefCommandLine> command_line)
{
	command_line->AppendSwitch("disable-spell-checking");
	//command_line->AppendSwitch("disable-extensions");
	command_line->AppendSwitch("disable-pdf-extension");
	command_line->AppendSwitch("enable-direct-write");
	command_line->AppendSwitch("allow-file-access-from-files");
	command_line->AppendSwitchWithValue("renderer-process-limit", "1");
	command_line->AppendSwitch("--disable-web-security");//关闭同源策略
	command_line->AppendSwitch("--enable-system-flash");//使用系统flash
}
```
