### ISSUE TITLE
刪除QCefView時整個程序退出

### ISSUE THREAD

**Issue by flcker** [tishion/QCefView#38]
我在我的Application裏使用了多個QCefView實例，但是當我刪除其中一個實例時，QMainWindow的closeEvent會被調用，然後程序退出。

**Comment by oopses** [comment]
我遇到了相同的问题，QCefview嵌入的窗口并不是系统主要窗口，，类似于QQ的会话窗口，关闭后，在列表重新打开一个会话，需要重新初始化。但是我看了官方的API以及QCefview的源码，关闭后进行browser的资源检测之后就shutdown了。对于下面的两个问题，大家有好的解决思路和方法吗？
1.窗口打开时的按需加载
2.非程序主窗口退出通知QCefview结束

**Comment by tishion** [comment]
Fixed in latest version.
