### ISSUE TITLE
Crash when starting test app 

### ISSUE THREAD

**Issue by meiry** [tishion/QCefView#40]
I compiled successfully the 
libcef_dll_wrapper.lib and this project 
but when i try to start the test app QCefViewTest
when is coming to :  ...\cef_binary_3.3396.1775.g5340bb0_windows32\libcef_dll\wrapper\libcef_dll_wrapper.cc
```
// Execute
  int _retval = cef_initialize(
      &args, &settings, CefAppCppToC::Wrap(application), windows_sandbox_info);
```
its just throw exception that looks like this in VS :  
![capture_cef](https://user-images.githubusercontent.com/1107316/41195670-d2dfbf0c-6c3a-11e8-86d5-cfdd2ff15125.PNG)

Any help will be appreciated 

Also i see it is looking for the source in :  
```
The debugger could not locate the source file 'Y:\work\CEF3_git\chromium\src\base\debug\debugger_win.cc'.
```
which i guess its your drive ... 

More info ,
i Tryed in the second run to compile the QCefView using MultiThreadedDebug (Multi-threaded Debug (/MTd)) 
as this is the default compilation state the  libcef_dll_wrapper compiled with 
i changed all the projects to Multi-threaded Debug (/MTd) 
but now i have this error :  
```
3>qtmaind.lib(qtmain_win.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in customcefview.obj
3>LIBCMTD.lib(initializers.obj) : warning LNK4098: defaultlib 'msvcrtd.lib' conflicts with use of other libs; use /NODEFAULTLIB:library
3>D:\Dev\my\cpp\cef\Qt\QCefView-master\QCefViewSDK\bin\Debug\\QCefViewTest.exe : fatal error LNK1319: 1 mismatches detected
3>Done building project "QCefViewTest.vcxproj" -- FAILED.
```

looking in the vcxproj files for example this : QCefView.vcxproj
i still can see that there is section that is using : MultiThreadedDLL 
Even though i changed every thing to Multi-threaded Debug (/MTd) 
i guess it have to do with the Qt compilation 
```
<AdditionalIncludeDirectories>.\GeneratedFiles;.;$(QTDIR)\include;.\GeneratedFiles\$(ConfigurationName);$(QTDIR)\include\QtCore;$(QTDIR)\include\QtGui;$(QTDIR)\include\QtWidgets;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <DebugInformationFormat />
      <TreatWChar_tAsBuiltInType>true</TreatWChar_tAsBuiltInType>
      <PrecompiledHeader>Use</PrecompiledHeader>
      <RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>
    </ClCompile>
    <Link>
      <SubSystem>Windows</SubSystem>
      <OutputFile>$(OutDir)\$(ProjectName).dll</OutputFile>
      <AdditionalLibraryDirectories>$(QTDIR)\lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <GenerateDebugInformation>true</GenerateDebugInformation>

```

**Comment by tishion** [comment]
Please refer to the project introduction.

**Comment by tishion** [comment]
Reformed the build system, try it.
