### ISSUE TITLE
QWidget: Must construct a QApplication before a QWidget

### ISSUE THREAD

**Issue by leftspace89** [tishion/QCefView#42]
>  'QCefViewTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\DataExchange.dll'. Cannot find or open the PDB file.
> 'QCefViewTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dcomp.dll'. Cannot find or open the PDB file.
> 'QCefViewTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\twinapi.appcore.dll'. Cannot find or open the PDB file.
> 'QCefViewTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rmclient.dll'. Cannot find or open the PDB file.
> 'QCefViewTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\TextInputFramework.dll'. Cannot find or open the PDB file.
> 'QCefViewTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\CoreUIComponents.dll'. Cannot find or open the PDB file.
> 'QCefViewTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\CoreMessaging.dll'. Cannot find or open the PDB file.
> 'QCefViewTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntmarta.dll'. Cannot find or open the PDB file.
> 'QCefViewTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\WinTypes.dll'. Cannot find or open the PDB file.
> 'QCefViewTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\WinTypes.dll'. Cannot find or open the PDB file.
> 'QCefViewTest.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\WinTypes.dll'
> QWidget: Must construct a QApplication before a QWidget
> Unhandled exception at 0x0FC69F67 (QCefView.dll) in QCefViewTest.exe: Fatal program exit requested.

**Comment by tishion** [comment]
Correct，and this is requirement of QT.

**Comment by leftspace89** [comment]
I mean even QCefViewTest example doesn't working. did you understand that  I used QT 5.11

**Comment by tishion** [comment]
@leftspace89  Please try with the latest version.
