### ISSUE TITLE
有关拖动窗口的问题

### ISSUE THREAD

**Issue by liuty2006** [tishion/QCefView#43]
![image](https://user-images.githubusercontent.com/4623059/47340127-e4ccc700-d6cf-11e8-8335-4818638070ff.png)
这个对于鼠标时可以拖动的，但对于触屏则不可以。怎么解决？

**Comment by tishion** [comment]
你可以先去看一下Windows是如何处理touch消息的
https://docs.microsoft.com/en-us/windows/desktop/wintouch/wm-touchdown

整个Demo只是用于提供一个Native和Web通信的例子，至于具体的某项功能，需要你自己去完成了。

**Comment by liuty2006** [comment]
谢谢！
还有一个问题，QCefView不支持有MP4内容的页面，怎么才能支持?

**Comment by oopses** [comment]
这个需要自己编译cef的源码来支持mp3 mp4等视频格式
