### ISSUE TITLE
cef3.3538+qt5.11.2+vs2017 编译后运行QCefViewTest崩溃

### ISSUE THREAD

**Issue by chenxiao1990** [tishion/QCefView#44]
1. 第一次崩溃是因为resource找不到目录，将qtdir的当前目录设置一下就找得到了
2. 第二次崩溃还是因为资源文件找不到，将resources里面的文件复制出来一份就好了
3. 第三次崩溃，加载不出来本地那个web，然后一直调用QCefViewBrowserHandler::OnRenderProcessTerminated,但是这个browser->GetMainFrame()->GetURL() 会返回null 
在cef3.3538+qt5.5+vs2013 也是一样。  不知道怎么回事了

**Comment by chenxiao1990** [comment]
这条路走不通的朋友可以自己使用cefsample写一个主要改动有
1. CefSettings settings;
settings.multi_threaded_message_loop = true;
设置多线程的消息，这样就不用调用那个阻塞住的CefRunMessageLoop
2. 工程的设置编译后执行参考cefsample
主要是把manifest附加到输入的exe上
试过了可以使用。仅献给卡在cef-qt这条路上的痛苦中的人

**Comment by looksoo** [comment]
使用release 试试， 或者在QCefView增加 manifest

**Comment by oopses** [comment]
首先对于官方的demo运行起来，然后再来对QCefview进行编译修改

**Comment by tishion** [comment]
I have reformed the build system, you can try the latest version.
