### ISSUE TITLE
It will be bolcked when program exits

### ISSUE THREAD

**Issue by hui-livio** [tishion/QCefView#49]
When my test program exits, it will block. When I debug, I found that after executing the "close_cv_.wait(lock);" statement of QCefViewBrowserHandler::CloseAllBrowsers(bool force_close), the program is blocked, and the program does not enter "void OnBeforeClose( CefRefPtr<CefBrowser> browser)" this function.
I am building the entire project using Qt5.6.3 +VS2013

**Comment by hui-livio** [comment]
你好，我在退出测试程序时候会阻塞住，我调试发现调用这个函数QCefViewBrowserHandler::CloseAllBrowsers(bool force_close)的最后一段代码close_cv_.wait(lock);之后就阻塞住了，而且没有进入QCefViewBrowserHandler::OnBeforeClose这个函数。我没有打开弹出的网页，只打开了一个百度界面，关闭就阻塞住了。我使用的是VS2013+Qt5.6.3编译的整个项目

**Comment by tishion** [comment]
can you reproduce it stably? If so please capture a dump file and share it with me.

**Comment by Fidark** [comment]
有解决吗，我也遇到了这个问题。环境是一样的。直接运行QCEFViewTest，退出不了。我现在的解决方案是在退出的时候用taskkill。
Do you have a solution? I also have this problem. The environment is the same. Run qcefviewtest directly, unable to exit.My current solution is to use taskkill when exiting.

**Comment by hui-livio** [comment]
我找到了解决办法，原因是cef关闭的流程不对，可以参考这个https://blog.csdn.net/sfhinsc/article/details/87540851

解决方法，在类CCefManager的releaseCef函数里面做出如下修改
void CCefManager::releaseCef()
{
  CefQuitMessageLoop();  // 先关闭cef3的事件循环，如果没有这个就会导致退出时候阻塞
  CefShutdown();       // 再关闭cef3
}
