### ISSUE TITLE
Don't support transparent html page

### ISSUE THREAD

**Issue by winsoft666** [tishion/QCefView#51]
attach file is a transparent html page, QCefView don't support render transparent backgroud.

[lrc.zip](https://github.com/tishion/QCefView/files/3920965/lrc.zip)

**Comment by tishion** [comment]
I don't think you can achieve the effect you want to do. You should know that the background is not rendered by the application not the browser engine. The browser content is drawn on the host widow which is a QWidget（actually a native window), so the background is drawn by the Qt UI framework. if you want the background to be transparent you need to change the Qt widget attribute and flags.

**Comment by winsoft666** [comment]
as I konw, only windowless render mode support transparent.
