### ISSUE TITLE
在退出时候子进程QCefWing无法关闭

### ISSUE THREAD

**Issue by hui-livio** [tishion/QCefView#52]

**Comment by tishion** [comment]
@yuanfeng1995 I noticed that you said you solved this problem by calling CefQuitMessageLoop but if you read the document of CefQuitMessageLoop you will know that  this is not correct fix.
```cpp
///
// Quit the CEF message loop that was started by calling CefRunMessageLoop().
// This function should only be called on the main application thread and only
// if CefRunMessageLoop() was used.
///
/*--cef()--*/
void CefQuitMessageLoop();
````
***This function should only be called on the main application thread and only if CefRunMessageLoop() was used.***

QCefView doesn't use cef message loop explicitly at all.

**Comment by keiler2018** [comment]
how to solve?
