### ISSUE TITLE
title 属性提示框无法显示

### ISSUE THREAD

**Issue by yuyuzhi** [tishion/QCefView#53]
网页中给元素设置title属性，title属性的内容没有tooltip显示

**Comment by tishion** [comment]
Sorry, @yuyuzhi, I think this is a front-end issue, not the problem of this project.

**Comment by yuyuzhi** [comment]
bug已经解决,解决思路:
QCefView 类中重载两个方法:
void focusInEvent(QFocusEvent* event) override;
void focusOutEvent(QFocusEvent* event) override;

设置CefBrowserHost 焦点解决。

**Comment by tishion** [comment]
@yuyuzhi  可否发起一个PR，把你的修改贡献出来？
