### ISSUE TITLE
QCefViewBrowserHandler::CloseAllBrowsers 阻塞

### ISSUE THREAD

**Issue by Jaredjin** [tishion/QCefView#55]
有时候不能正常退出，阻塞在close_cv_.wait(lock); 
直接在QDialog原生窗口上点关闭，出现情况比较少，但是通过this->reject()等一直都是阻塞状态。

**Comment by happysi** [comment]
void
QCefViewBrowserHandler::CloseAllBrowsers(bool force_close)
{
  // If all browsers had been closed, then return
  {
	  std::unique_lock<std::mutex> lock(mtx_);
	  if (!browser_count_) {
		return;
	  }

	  // Flip the closing flag
	  is_closing_ = true;

	  // Close all popup browsers if any
	  if (!popup_browser_list_.empty()) {
		for (auto it = popup_browser_list_.begin(); it != popup_browser_list_.end(); ++it)
		  (*it)->GetHost()->CloseBrowser(force_close);
	  }

	  if (main_browser_)
		// Request that the main browser close.
		main_browser_->GetHost()->CloseBrowser(force_close);
  }
  // Wait for the browser to be closed
  MSG msg;
  while (GetMessage(&msg, NULL, 0, 0)) {
    DispatchMessage(&msg);
    std::unique_lock<std::mutex> lock(mtx_);
    if (!browser_count_) {
      break;
    }
  }
  //close_cv_.wait(lock);
}
这句close_cv_.wait(lock);阻断了cef向顶层窗口发送的WM_CLOSE的处理 换个方式让它有处理消息的机会
参考cef的关闭流程
void CefBrowserHostImpl::PlatformCloseWindow() {
  if (window_info_.window != NULL) {
    HWND frameWnd = GetAncestor(window_info_.window, GA_ROOT);
    PostMessage(frameWnd, WM_CLOSE, 0, 0);
  }
}

**Comment by tangduoling** [comment]
还是会卡在那里。

**Comment by happysi** [comment]
参考下cef3的标准释放流程：（切记cefview不能直接释放）
CefLifeSpanHandler类中
virtual bool DoClose(CefRefPtr<CefBrowser> browser) { return false; } 
需要改下代码添加个函数来调用  pQCefViewHandler_->onClose();

**Comment by tishion** [comment]
fixed in this commit: 6f5715e2dc3dbe2ee94e6c00c93dfd202544fd2c
