### ISSUE TITLE
有些地方不是很明白

### ISSUE THREAD

**Issue by hailunchina** [tishion/QCefView#56]
1.可以看到工程里面有4个头文件分别是(QCefView.h/QCefSetting.h/QCefQuery.h/QCefEvent.h),
表示不知道这4个头文件的意义是什么,作用是什么,
2.我在自己创建的QT工程中,直接引入以上4个头文件,还是说需要指定的功能时候就去修改QCefView的源码,来实现?这块有点迷糊,如果是通过QCefView源码来修改,那么上面的4个文件存在的意义是什么?我就可以直接修改QCefView源码即可实现.
3.如果不是修改QCefView源码,而是通过上面4个文件实现功能修改和扩展的话,那么,提供的案例程序(QCefViewTest),是否可以多丰富些内容,比如JS回调处理,下载回调处理,键盘回调处理,等等相关回调的案例.谢谢.

**Comment by tishion** [comment]
hi @hailunchina， 
QCefView的初衷就是封装CEF，封装除了隐藏内部细节，还要暴露原来的cef相关的控制接口，比如cef初始化的参数等
QCefView.h：Qt封装的CEF控件，通过该对象可以实现控制cef窗口的各种属性和表现
QCefSetting.h：封装CEF相关的设置，这些都是独立的函数，可以直接调用，并且影响是全局的
QCefQuery.h：表示一个从javascript中用QCefQuery发起的请求在C++代码中的结构（参见demo）
QCefEvent.h：表示一个从C++代码中用triggerEvent触发的事件，该事件会进入Javascript被相应的listener处理（如果存在）

简单一点：
QCefSetting，控制Cef的初始化参数
native -> JS 是通过QCefEvent实现
JS -> native是通过QCefQuery实现（还有其他方法）
