### ISSUE TITLE
LoadString(strContent, strUrl) deprecated in the very last version of CEF

### ISSUE THREAD

**Issue by ShelleyLake** [tishion/QCefView#57]
@tishion 
First of all thanks for your great example.
I've a problem. In the latest version of CEF the "LoadString" has been deprecated.
Do you know how to deal with that?

`pQCefViewHandler_->GetBrowser()->GetMainFrame()->LoadString(strContent, strUrl);`

**Comment by tishion** [comment]
If you need to use the latest CEF, you need to adjust the interface exposed by QCefView. 

As you see there is no LoadString method but you can still use LoadUrl to achieve the same goal.
Just code as follows:

```cpp
  // prepare the html content
  std::ostringstream oss;
  oss << "<html><body bgcolor=\"white\">"
      << "<h2>Failed to load URL: " << url << " </h2>"
      << "<h2>Error: " << msg << "(" << errorCode << ")</h2>"
      << "</body></html>";
  std::string data = oss.str();

  // encode the html content with base64 first, and then encode the base64 content with Url encoding
  data = CefURIEncode(CefBase64Encode(data.c_str(), data.size()), false).ToString();

  // then add prefix "data:text/html;base64" to the encoded content 
  data = "data:text/html;base64," + data;

  // use the encoded content above as Url and pass it to the LoadURL method
  frame->LoadURL(data);
````

hope this is not too late.
