### ISSUE TITLE
示例 onQCefUrlRequest 无响应

### ISSUE THREAD

**Issue by AdonLuo** [tishion/QCefView#58]
你好，目前在运行测试例子的时候，发现点击 qcef://test/a/b 无响应问题。
调试发现之前的绑定是信号未被触发，SchemeHandler::Open 方法没有进入，另外在点击qcef://test/a/b 的时候调试进入到 new SchemeHandler(nullptr); 这个参数应该是需要有个窗口指针，但是我看了注册的时候未找到相关可以使用的窗口，比较疑惑，目前无法解决，特此请教，望解惑

**Comment by tishion** [comment]
已修复

**Comment by AdonLuo** [comment]
@tishion 感谢你的回复以及解决了这个问题，继续学习使用中，目前还遇到几个问题在摸索中，1.调试的时候关闭程序，进程还未结束（vs2015+Qt5.9.3环境， 现象未退出调试，新创建的子窗未跟着关闭）；2.新增了前进返回按钮操作，但是使用返回每次都直接到第一次的url,监听了onLoadingStateChanged ，canGoForward参数一直未false;3.我使用这个项目最终的需求是想在网页页面上层，在展示一个窗体（无标提栏、无任务栏）播放视频监控用的，为的是解决谷歌下无法使用ocx问题，但是目前操作无法实现，自定义子窗要么显示在Qcefview 底层，要么是加上Qt::Tool出现一些其他问题，今天在这个关闭的issues中也看到很多同行遇到的问题需求，希望能找到合适的解决办法，再次感谢！
