### ISSUE TITLE
使用vs2015+cef_binary_80.0.4+g74f7b0c+chromium-80.0.3987.122_windows32+QT5.9.9调试运行抛异常

### ISSUE THREAD

**Issue by twallpasser** [tishion/QCefView#59]
线程名：
CrBrowserMain
异常描述：
0x12864848 (libcef.dll) (QCefViewTest.exe 中)处有未经处理的异常: 0xC000001D: Illegal Instruction。

**Comment by longjm** [comment]
你的问题解决了？？？
cef_binary_78.3.9gc7345f2chromium-78.0.3904.108_windows32 也出现这个问题，是不是只支持76.1.13呢

**Comment by tishion** [comment]
注意32位和64位的区别

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tangduoling** [comment]
把调试目录改成exe所在目录就可以了。

**Comment by tishion** [comment]
Please remember to set working directory to $(OutDir) if you are DEBUGGING with VS
