### ISSUE TITLE
QCefView 不能正常关闭

### ISSUE THREAD

**Issue by zajzhuaijun** [tishion/QCefView#62]
QCefViewBrowserHandler::CloseAllBrowsers 阻塞 ，点击窗口右上角可以正常 关闭，点击自己的按钮，触发close，就阻塞，请问这个怎么解决

**Comment by chengjianxi** [comment]
```
::PostMessage((HWND)winId(), WM_CLOSE, 0, 0);
//PostQuitMessage(0);
//this->close();
//qApp->quit();
```
最后用PostMessage解决了

**Comment by zajzhuaijun** [comment]
我也测试了，没用，我后来自己解决了，改变了资源释放




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tishion/QCefView"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月14日(星期二) 上午9:47
收件人:&nbsp;"tishion/QCefView"<QCefView@noreply.github.com&gt;;
抄送:&nbsp;"天马行空"<978206970@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tishion/QCefView] QCefView 不能正常关闭 (#62)





 
::PostMessage((HWND)winId(), WM_CLOSE, 0, 0); //PostQuitMessage(0); //this-&gt;close(); //qApp-&gt;quit();
 最后用PostMessage解决了

**Comment by chengjianxi** [comment]
请问方便把代码贴出了吗

**Comment by zajzhuaijun** [comment]
改的源码，方便的时候贴出来




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tishion/QCefView"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月14日(星期二) 上午9:52
收件人:&nbsp;"tishion/QCefView"<QCefView@noreply.github.com&gt;;
抄送:&nbsp;"天马行空"<978206970@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tishion/QCefView] QCefView 不能正常关闭 (#62)





 
请问方便把代码贴出了吗

**Comment by happysi** [comment]
参考下CefLifeSpanHandler中的DoClose　注释上有cef3的标准退出流程　QCefview的在析构时进行的CloseAllBrowsers大概率会lock住进程退不掉

**Comment by 0exception** [comment]
> 改的源码，方便的时候贴出来
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "tishion/QCefView" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月14日(星期二) 上午9:52 收件人:&nbsp;"tishion/QCefView"<QCefView@noreply.github.com&gt;; 抄送:&nbsp;"天马行空"<978206970@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [tishion/QCefView] QCefView 不能正常关闭 (#62) 请问方便把代码贴出了吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问下怎么解决的？

**Comment by keiler2018** [comment]
进程不退出 怎么破

**Comment by tishion** [comment]
fixed in this commit: 6f5715e2dc3dbe2ee94e6c00c93dfd202544fd2c
