### ISSUE TITLE
你好，我现在遇到一个mp4的播放问题，cef是支持mp4的，QCefViewTest却不能正常播放

### ISSUE THREAD

**Issue by orgcrab** [tishion/QCefView#68]
我使用了cef3809版本，也加入了mp4支持，用cefclient测试，mp4已可以正常播放，但是QCefViewTest打开视频网页却提示flash插件问题，这个是需要设置什么么

**Comment by tishion** [comment]
你确定你播放的是MP4？请把你的测试页面内容或者URL发出来。

**Comment by orgcrab** [comment]
打开的是爱奇艺

**Comment by orgcrab** [comment]
一些直播平台网页也是一样，感觉好像QCefView是固定的用flash去播放的，因为打开这些页面之后都是提示的flash插件问题

**Comment by tishion** [comment]
你把问题描述清楚，如果你说用cefclient能播放，截个图给我看看。如果你没有测试过就过来发issue，让我帮你去test，这是浪费我的时间。

**Comment by orgcrab** [comment]
![4F035BDE-C4E3-4893-B953-3734CC217853](https://user-images.githubusercontent.com/21237213/93335978-be7f1a00-f859-11ea-8b6f-f1340773f152.png)
这张是QCefViewTest打开虎牙的截图
![image](https://user-images.githubusercontent.com/21237213/93336233-0f8f0e00-f85a-11ea-9d82-cfef074c8fce.png)
这张是cefclient打开虎牙的截图,
我对比了一下CefSettings的信息，QCefViewTest是默认设置了UA的，把UA去掉后就可以播放了，我是刚接触浏览器，属于新手，我理解UA应该是用来做身份确认的，应该没有影响才对，是不是网页自己根据UA做了播放方式判断？耽误你时间了也非常抱歉哈

**Comment by tishion** [comment]
你能解决问题就行了。

UA不同，视频播放网站会使用不同的视频格式和播放模式，chrome是不支持mp4播放的，你看到能播放的肯定不是mp4格式。对于非chrome的浏览器，网站会使用flash播放，所以你的问题跟mp4没有一点关系。

**Comment by orgcrab** [comment]
嗯嗯，谢谢啦，mp4是我说的不准确，应该是h264
