### ISSUE TITLE
static build with static runtime

### ISSUE THREAD

**Issue by muffmolch** [tishion/QCefView#7]
Hi
I'm trying to use a static qt lib using static runtime to link against your QCefView. But it fails. First of all we turned of Iterator debugging in VS. Thus the sandbox librarys devlivered by cef dows not link.

Is it possible to use cef in a dll and the QCefView as static lib with static runtime?

**Comment by tishion** [comment]
Hi @muffmolch.

QCefView depends on not only QT library but also the CEF library. So now you have got the static QT lib linked with static runtime, you also need to build the libcef_dll_wrapper.lib with static link to runtime libs.

1.Download the CEF binary distributed version from: https://cefbuilds.com/ 
2.Generate the Visual studio solution files
3 Make sure you build the libcef_dll_wrapper.lib with MT /MTd
4. Copy all the cef output to the dep folder of QCefView solution
5. Change all the configurations of the projects in QCefView solution to MT /MTd

Build it. If no errors. now you should get QCefView.dll this is a DLL with static link to runtime.

Then you can try to change the configuration type of QCefView project to static library.

And then build it again. Good luck!

For sandbox.lib  I think this is built by the cefbuild.com, so we don't have the source code. If you really want to use it you need to build CEF totally by yourself (check out  chromium project.)

if any problems please let me know.

**Comment by muffmolch** [comment]
Hi @tishion 
Thanks. Meanwhile I got it. I just built cef and your lib in with /mt(d). In addition I complied and linked your lib as static lib (removing the decl-call-define). Your example is set up for the qt dll version. Thus I just copied your code into my source tree and after some self written cmake magic I got all needed static libs to get it run...

Thanks
SirAnn

**Comment by tishion** [comment]
Cool!   That's awsome! But you know I didn't make a good design about the  URL schema handler. So if you want to extent this feature you need to revamp it. 

Thanks!
