### ISSUE TITLE
窗口点击关闭后进程并未退出

### ISSUE THREAD

**Issue by oopses** [tishion/QCefView#71]
Qt 5.9.6(msvc 32)+vs2015+76.1.13+gf19c584+chromium-76.0.3809.132_windows32+win7
编译成功后运行QcefViewText.exe，然后点击窗口关闭，打开任务管理器 QcefViewText.exe QCefWing.exe两个进程仍然还在运行中

**Comment by happysi** [comment]
参考下cef3的标准释放流程：（切记cefview不能直接释放）
CefLifeSpanHandler类中
virtual bool DoClose(CefRefPtr browser) { return false; }

**Comment by tishion** [comment]
fixed in this commit: 6f5715e2dc3dbe2ee94e6c00c93dfd202544fd2c
