### ISSUE TITLE
我下载的cef版本是cef_binary_86.0.21+g6a2c8e7+chromium-86.0.4240.183_windows64，其中CefFrame中没有LoadString这个函数，导致QCefView编译失败，请问这个函数应该用什么替代呢？

### ISSUE THREAD

**Issue by liudanx** [tishion/QCefView#73]
我下载的cef版本是cef_binary_86.0.21+g6a2c8e7+chromium-86.0.4240.183_windows64，其中CefFrame中没有LoadString这个函数，导致QCefView编译失败，请问这个函数应该用什么替代呢？

**Comment by happysi** [comment]
移除LoadString这个方法就行了
      //pQCefViewHandler_->GetBrowser()->GetMainFrame()->LoadString(strContent, strUrl);
      pQCefViewHandler_->GetBrowser()->GetMainFrame()->LoadURL(strUrl);

**Comment by liudanx** [comment]
多谢，我这边将cef替换为 cef_binary_76.1.13+gf19c584+chromium-76.0.3809.132_windows64_minimal 了，但是遇到了一个更棘手的问题，我在关闭客户端的时候，进程会卡主5分钟左右，调试的时候发现它是卡在了
`void
QCefViewBrowserHandler::CloseAllBrowsers(bool force_close)
{
  // If all browsers had been closed, then return
  std::unique_lock<std::mutex> lock(mtx_);
  if (!browser_count_) {
    return;
  }

  // Flip the closing flag
  is_closing_ = true;

  // Close all popup browsers if any
  if (!popup_browser_list_.empty()) {
    for (auto it = popup_browser_list_.begin(); it != popup_browser_list_.end(); ++it)
      (*it)->GetHost()->CloseBrowser(force_close);
  }

  if (main_browser_)
    // Request that the main browser close.
    main_browser_->GetHost()->CloseBrowser(force_close);

  // Wait for the browser to be closed
  close_cv_.wait(lock);
}`
wait的位置，有什么想法可以分享吗

**Comment by tishion** [comment]
> 我下载的cef版本是cef_binary_86.0.21+g6a2c8e7+chromium-86.0.4240.183_windows64，其中CefFrame中没有LoadString这个函数，导致QCefView编译失败，请问这个函数应该用什么替代呢？

按照 @happysi 的修改方式修改就行了。

> 多谢，我这边将cef替换为 cef_binary_76.1.13+gf19c584+chromium-76.0.3809.132_windows64_minimal 了，但是遇到了一个更棘手的问题，我在关闭客户端的时候，进程会卡主5分钟左右，调试的时候发现它是卡在了
> `void
> QCefViewBrowserHandler::CloseAllBrowsers(bool force_close)
> {
> // If all browsers had been closed, then return
> std::unique_lockstd::mutex lock(mtx_);
> if (!browser_count_) {
> return;
> }
> 
> // Flip the closing flag
> is_closing_ = true;
> 
> // Close all popup browsers if any
> if (!popup_browser_list_.empty()) {
> for (auto it = popup_browser_list_.begin(); it != popup_browser_list_.end(); ++it)
> (*it)->GetHost()->CloseBrowser(force_close);
> }
> 
> if (main_browser_)
> // Request that the main browser close.
> main_browser_->GetHost()->CloseBrowser(force_close);
> 
> // Wait for the browser to be closed
> close_cv_.wait(lock);
> }`
> wait的位置，有什么想法可以分享吗

这个bug一直没有修复，十分抱歉。
后续会推出macOS/Windows跨平台版本，已经解决了这个问题。

**Comment by tishion** [comment]
Fixed
