### ISSUE TITLE
Compile Error: API Deprecated

### ISSUE THREAD

**Issue by Andney** [tishion/QCefView#76]
These apis was removed:

```cpp
CefRenderProcessHandler::OnRenderThreadCreated();
CefBrowserProcessHandler::OnRenderProceeThreadCreated();
```

Reason : [Remove render thread created callbacks (see issue #2498) ](https://github.com/chromiumembedded/cef/commit/280c9127c1fcec485a53bd3ef44e581655a4ab7b#diff-5e0472c01a360dcbfae29076862b2772c8164e8c8f2ea274cc178d8116d83f8e)

**Comment by tishion** [comment]
Same problem as #78, let's move to this issue thread to discuss.
