### ISSUE TITLE
delete QCefView 后再次使用crash

### ISSUE THREAD

**Issue by 0exception** [tishion/QCefView#87]
父窗口析构后，delete了QCefView -》closeallbrowser -》CEFShutDown 
进程没有退出，再次走一遍父窗口 初始化QcefView流程 crash

**Comment by 0exception** [comment]
if (!reverse) {
    reverse = true;
    ui.cefContainer->layout()->removeWidget(cefview);
    delete cefview;
    cefview = nullptr;
  } else {
    cefview = new CustomCefView("https://www.baidu.com", this);   //crash  at cef_initialize function
    ui.cefContainer->layout()->addWidget(cefview);
  }

**Comment by Liminglyq** [comment]
你好 这个问题怎么解决的？
